name = "Minimal"
author = "Vartroc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cde1b8c3f25034b23b4ebdcdf8fed487c7f7c92d225c94080f41f65c1669b15"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
