name = "Minimal"
author = "Vartroc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74394e9be18d7434efd9578d6479e4142659ae24ebb3868c5950dea65ce0650a"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
