name = "Minimal"
author = "Vartroc"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "07976aed31e5840b7b0b52450179e68ecc0c77c7ceb637b6caaa98ad23038d6f"

[versions]
fabric = "0.16.0"
minecraft = "1.20.1"
